### ISSUE TITLE
limit datatype dropdown menu with xsd:  vocab options

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/ruminator#1]
Hi, could you please limit the datatypes in the dropdown menu to:
- xsd:string
- xsd:decimal
- xsd:float
- xsd:integer
- xsd:gYear

(in this order)

while retaining the possibility to manually add another datatype.

**Comment by mmmenno** [comment]
Done. Other datatypes can be added manually in the json - these are not validated. Datatypes without the `xsd:` prefix are prefixed anyway.
