### ISSUE TITLE
remove double entry of valueUrl/ csvw:value

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/ruminator#2]
Hi!

Currently, there is a row for both `valueUrl` and a row for `csvw:value`. However, this should be an either or option: if someone uses a `valueUrl` he/she cannot use `csvw:value` as well. (perhaps use a drown-down?)

**Comment by mmmenno** [comment]
I made a dropdown, but only in virtual columns, right?
And regular columns never have aboutUrls?

**Comment by mmmenno** [comment]
Ok, i'll close it for now, please reopen if I was wrong about the regular columns never having aboutUrls!
